// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	UserID       *string `json:"UserId"`
	ProductID    *string `json:"ProductId"`
	ProductName  *string `json:"ProductName"`
	ProductInfo  *string `json:"ProductInfo"`
	ProductImage *string `json:"ProductImage"`
	ProductStock *int    `json:"ProductStock"`
	ProductPrice *int    `json:"ProductPrice"`
	ProductSell  *int    `json:"ProductSell"`
	CreatedDate  *string `json:"CreatedDate"`
	LastUpdate   *string `json:"LastUpdate"`
}

type ResponseSelectUser struct {
	UserID      *string    `json:"user_id"`
	UserEmail   *string    `json:"user_email"`
	UserName    *string    `json:"user_name"`
	UserImage   *string    `json:"user_image"`
	UserStatus  *string    `json:"user_status"`
	CreatedDate *string    `json:"created_date"`
	LastUpdate  *string    `json:"last_update"`
	Products    []*Product `json:"products"`
}

type ResponseSelectUsers struct {
	User   []*User `json:"user"`
	Status *string `json:"status"`
	Code   *int    `json:"code"`
}

type User struct {
	UserID      *string    `json:"user_id"`
	UserEmail   *string    `json:"user_email"`
	UserName    *string    `json:"user_name"`
	UserImage   *string    `json:"user_image"`
	UserStatus  *string    `json:"user_status"`
	CreatedDate *string    `json:"created_date"`
	LastUpdate  *string    `json:"last_update"`
	Products    []*Product `json:"products"`
}
